= Introduction
:stem:
:toc:
:docinfo:
:sourcedir: ../../../samples/src/main/java
:outdir: ../../../target/site/docs
:icons: font

== Introduction


Genetics4j uses a standard version of Genetic Algorithms. However many steps are highly configurable.

Here is a diagram of the main flow:


[ditaa]
....
                             Startint point
                                   *
                                   |
                                   |
                                   |
                                   v
                     /-----------------------------\
                     | Generate initial population |
                     \-----------------------------/
                                   |
                                   |
                                   v
                          /------------------\
                          | Evaluate Fitness |
                          \------------------/
                                   |
                                   v
                           +---------------+
                           |{c}            |  Yes
   +---------------------->|  Is it done?  |-----------------------------> The End
   |                       |               |                              
   |                       +---------------+                              
   |                               |
   |                               | No
   |                               |
   |                 +-------------+---------------+
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |         /----------------\                    |
   |         | Select Parents |                    |
   |         \----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /-----------------\                    |
   |        | Combine Parents |                    |
   |        \-----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /-----------------\                    |
   |        | Mutate Children |                    |
   |        \-----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /------------------\                   |
   |        | Evaluate Fitness |                   |
   |        \------------------/                   |
   |                 |                             |
   |                 |                             |
   |      Offsprings |                             | Current Population
   |                 +------------+----------------+
   |                              |
   |                              |
   |                              v
   |                 /--------------------------\
   |                 |   Replacement Strategy   |
   |                 | Generate Next Population |
   |                 \--------------------------/
   |                              |
   |                              |
   |                              |
   +------------------------------+

....



This is a standard flow for a genetic algorithm. At each generation, we will select some parents who will then generate some offsprings that will be mutated. And finally, a new generation will be created as defined by the _replacement strategy_ from both offsprings and previous generation. The process will stop as soon as the termination conditions are met.

## Concepts

### Genotype

An individual, which represent a solution, is called a link:https://en.wikipedia.org/wiki/Genotype[genotype]. A genotype can be composed of multiple chromosomes of different nature.
A chromosome can encode data in different ways:

* Binary representation
* Integer values
* Real values
* Tree
* Linear sequences (Genetic Programming)


The genotype is defined through the link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html[Evolutionary Algorithm Configuration] class where one can define the link:../apidocs/net/bmahe/genetics4j/core/spec/GenotypeSpec.html#chromosomeSpecs()[ChromosomeSpecs] class


#### Chromosomes

The _core_ module provides the following types of chromosomes out of the box:

* Bits based chromosomes. See link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/BitChromosomeSpec.html[BitChromosomeSpec]
* Integer based chromosomes. See link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/IntChromosomeSpec.html[IntChromosomeSpec]
* Float based chromosomes. See link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/FloatChromosomeSpec.html[FloatChromosomeSpec]
* Double based chromosomes. See link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/DoubleChromosomeSpec.html[DoubleChromosomeSpec]



### Fitness

Fitness of an individual establish of good of a solution it is. It can be of any type as long as it extends _java.lang.Comparable_. Which means one could use a _Double_ for a single measure of the fitness as well as more complex data structures for cases such as *Multi-Object Optimizations*.

The link:../apidocs/net/bmahe/genetics4j/core/Fitness.html[fitness] function is established in the link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html#fitness()[EAConfiguration] class


### Population Generation

Individuals are generated based on their chromosomes' definitions. Each chromosome ships with a default factory. Chromosome factories are defined as link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactory.html[ChromosomeFactory], which are configured in the link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactoryProvider.html[ChromosomeFactoryProvider], which itself is configured in the method link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html#chromosomeFactoryProvider[chromosomeFactoryProvider()] of link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html[EAExecutionContext]

One could override the way Individuals are generated through either:

* Specify a generation method in link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html#populationGenerator()[populationGenerator()]
* Provide their own link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactoryProvider.html[ChromosomeFactoryProvider] in link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html#chromosomeFactoryProvider[EAExecutionContext]

### Selection Policy

The goal of a link:../apidocs/net/bmahe/genetics4j/core/spec/selection/SelectionPolicy.html[SelectionPolicy] is to select a set of individuals. It is an important piece of an Evolutionary Algorithm as it helps apply pressure towards the desired goal.

The current set of available selection policies are:

* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/DoubleTournament.html[DoubleTournament] - It implements a double tournament as specified in the paper _Fighting Bloat With Nonparametric Parsimony Pressure_ <<fbwnpp>>. It is used in _Genetic Programming_ to control bloat by combining tournaments based on fitness with tournaments based on parsimony.
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/MultiSelections.html[MultiSelections] - This is a wrapper for combining multiple selection policies. The set of individuals to select will be equally spread across each selection policy
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/MultiTournaments.html[MultiTournaments] - This operator enables to chain multiple link:../apidocs/net/bmahe/genetics4j/core/spec/selection/Tournament.html[Tournament]s
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/ProportionalTournament.html[ProportionalTournament] - It implements a proportional tournament as specified in the paper _Fighting Bloat With Nonparametric Parsimony Pressure_ <<fbwnpp>>. It is used in _Genetic Programming_ to control bloat by combining tournaments based on fitness with tournaments based on parsimony.
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/RandomSelection.html[RandomSelection] - Randomly select individuals with a uniform distribution
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/RouletteWheel.html[RouletteWheel] - Also called _Fitness Proportionate Selection_ where the probability of selection of an individual is proportionate to its fitness
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/SelectAll.html[SelectAll] - Pass through and will select whatever individuals it can fit in
* link:../apidocs/net/bmahe/genetics4j/core/spec/selection/Tournament.html[Tournament] - It implements _k-tournament_ selection where _k_ invidivuals are picked from the population and the fittest one is selected. Selection pressure will vary bases on the value of _k_


### Combination Policy

The goal of a link:../apidocs/net/bmahe/genetics4j/core/spec/combination/CombinationPolicy.html[CombinationPolicy] is to combine two individuals and create zero, one or more offsprings.

The current set of available combination policies are:

* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/SinglePointCrossover.html[SinglePointCrossover] - A random cut is made, separating each parent in half. Offsprings are created by combining each halves
* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/MultiPointCrossover.html[MultiPointCrossover] - This is an extension of the Single Point Crossover where _n_ cuts are made and the offsprings are created by combining each sections
* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/OrderCrossover.html[OrderCrossover] (OX) - This operator assumes a path representation in the chromosome and construct an offspring by selecting a subtour in one parent and preserving the relative order of the other parent. This is only available for chromosomes of type link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/IntChromosomeSpec.html[IntChromosomeSpec]
* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/PickFirstParent.html[PickFirstParent] - The first parent is always chosen as the offspring
* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/EdgeRecombinationCrossover.html[EdgeRecombinationCrossover] (ERX) - This operator assumes a path representation in the chromosome and construct an offspring with the aim of preserving the edges from the parents as much as possible. This is only available for chromosomes of type link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/IntChromosomeSpec.html[IntChromosomeSpec]
* link:../apidocs/net/bmahe/genetics4j/core/spec/combination/MultiCombinations.html[MultiCombinations]- This is a wrapper for combining multiple combination policies. It will select a combination policy randomly with a uniform distribution


### Mutation

The goal of a link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/MutationPolicy.html[MutationPolicy] is to maintain diversity and allow undirected jumps to slightly different areas of the search space.

The current set of available mutation policies are:

* link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/RandomMutation.html[RandomMutation] - Randomly change a value of the chromosomes. It might be flipping bits in the case of bit chromosomes or changing to a different value for int chromosomes
* link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/SwapMutation.html[SwapMutation] - Randomly change two values of the chromosomes
* link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/PartialMutation.html[PartialMutation] - Apply a link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/MutationPolicy.html[MutationPolicy] for a very specific chromosome of the genotype
* link:../apidocs/net/bmahe/genetics4j/core/spec/mutation/MultiMutation.html[MultiMutation] - This is a wrapper for combining multiple mutation policies. It will select a mutation policy randomly with a uniform distribution


### Termination

link:../apidocs/net/bmahe/genetics4j/core/spec/termination/Termination.html[Termination] responsibility is determine whether or not the evolution process should continue or not.
Termination conditions could be based on any criteria, be it computation time, diversity in the population, reaching a specific fitness value or a combination of those.


link:../apidocs/net/bmahe/genetics4j/core/spec/termination/Terminations.html[Terminations] is a helper class which provides a few out of the box helpful termination conditions.


### Replacement Strategy

The link:../apidocs/net/bmahe/genetics4j/core/spec/replacement/ReplacementStrategy.html[replacement strategy] is crucial for driving the process as it specifies how to generate the next generation based on the current population and the offsprings.

The current set of available replacement strategies are:

* link:../apidocs/net/bmahe/genetics4j/core/spec/replacement/Elitism.html[Elitism] - The best individuals of respectively, the current generation and the mutated offsprings, are retained for the next generation.
* link:../apidocs/net/bmahe/genetics4j/core/spec/replacement/GenerationalReplacement.html[GenerationalReplacement] - The best individuals of the mutated offsprings are retained for the next generation and the current population is discarded.
* link:../apidocs/net/bmahe/genetics4j/core/spec/replacement/DeleteNLast.html[DeleteNLast] - The _N_ weakest invidivuals of the current population are discarded and replaced by the best offsprings.





[bibliography]
== References

- [[[fbwnpp]]] Sean Luke, Liviu Panait. Fighting Bloat With Nonparametric Parsimony Pressure
