= Introduction
:stem:
:toc:
:docinfo:
:sourcedir: ../../../samples/src/main/java
:outdir: ../../../target/site/docs
:icons: font

== Introduction


Genetics4j uses a standard version of Genetic Algorithms. However many steps are highly configurable.

Here is a diagram of the main flow:


[ditaa]
....
                             Startint point
                                   *
                                   |
                                   |
                                   |
                                   v
                     /-----------------------------\
                     | Generate initial population |
                     \-----------------------------/
                                   |
                                   |
                                   v
                          /------------------\
                          | Evaluate Fitness |
                          \------------------/
                                   |
                                   v
                           +---------------+
                           |{c}            |  Yes
   +---------------------->|  Is it done?  |-----------------------------> The End
   |                       |               |                              
   |                       +---------------+                              
   |                               |
   |                               | No
   |                               |
   |                 +-------------+---------------+
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |         /----------------\                    |
   |         | Select Parents |                    |
   |         \----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /-----------------\                    |
   |        | Combine Parents |                    |
   |        \-----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /-----------------\                    |
   |        | Mutate Children |                    |
   |        \-----------------/                    |
   |                 |                             |
   |                 |                             |
   |                 v                             |
   |        /------------------\          /--------------------\
   |        | Evaluate Fitness |          | Current population |
   |        \------------------/          \--------------------/
   |                 |                             |
   |                 |                             |
   |                 +------------+----------------+
   |                              |
   |                              |
   |                              v
   |                 /--------------------------\
   |                 |    Evolution Strategy    |
   |                 | Generate Next Population |
   |                 \--------------------------/
   |                              |
   |                              |
   |                              |
   +------------------------------+

....

This is a standard flow for a genetic algorithm. At each generation, we will select some parents who will then generate some offsprings that will be mutated. And finally, a new generation will be created as defined by the _evolution strategy_ from both offsprings and previous generation. The process will stop as soon as the termination conditions are met.

## Concepts

### Genotype

An individual, which represent a solution, is called a link:https://en.wikipedia.org/wiki/Genotype[genotype]. A genotype can be composed of multiple chromosomes of different nature.
A chromosome can encode data in different ways:

* Binary representation
* Integer values
* Real values
* Tree
* Linear sequences (Genetic Programming)


The genotype is defined through the link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html[Evolutionary Algorithm Configuration] class where one can define the link:../apidocs/net/bmahe/genetics4j/core/spec/GenotypeSpec.html#chromosomeSpecs()[ChromosomeSpecs] class


#### Chromosomes

The _core_ module provides the following types of chromosomes out of the box:

* Integers based chromosomes. See link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/BitChromosomeSpec.html[BitChromosomeSpec]
* Bits based chromosomes. See  link:../apidocs/net/bmahe/genetics4j/core/spec/chromosome/IntChromosomeSpec.html[IntChromosomeSpec]


### Fitness

Fitness of an individual establish of good of a solution it is. It can be of any type as long as it extends _java.lang.Comparable_. Which means one could use a _Double_ for a single measure of the fitness as well as more complex data structures for cases such as *Multi-Object Optimizations*.

The link:../apidocs/net/bmahe/genetics4j/core/Fitness.html[fitness] function is established in the link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html#fitness()[EAConfiguration] class


### Population Generation

Individuals are generated based on their chromosomes' definitions. Each chromosome ships with a default factory. Chromosome factories are defined as link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactory.html[ChromosomeFactory], which are configured in the link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactoryProvider.html[ChromosomeFactoryProvider], which itself is configured in the method link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html#chromosomeFactoryProvider[chromosomeFactoryProvider()] of link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html[EAExecutionContext]

One could override the way Individuals are generated through either:

* Specify a generation method in link:../apidocs/net/bmahe/genetics4j/core/spec/EAConfiguration.html#populationGenerator()[populationGenerator()]
* Provide their own link:../apidocs/net/bmahe/genetics4j/core/chromosomes/factory/ChromosomeFactoryProvider.html[ChromosomeFactoryProvider] in link:../apidocs/net/bmahe/genetics4j/core/spec/EAExecutionContext.html#chromosomeFactoryProvider[EAExecutionContext]

### Selection


### Combination


### Mutation


### Termination


### Evolution Strategy
